#message: ${MESSAGE_CONTENT}
#author: ${AUTHOR_NAME}
#version: ${SERVICE_VERSION}
#description: ${SERVICE_DESCRIPTION}
#organization: ${ORG_NAME}


message: this is from config server repo feature branch1
author: sai
serviceversion: 1.0
servicedescription: feature branch1
orgname: tfs
